import { createActions } from 'redux-actions'

import {
    ADD_ORIGINAL_IMAGES,
    ADD_PRODUCT_ID,
    ADD_PRODUCT_FORM_ID,
    ADD_ENDPOINT,
    ADD_TEMPLATE_TO_PAGE,
    REMOVE_TEMPLATE_FROM_PAGE,
    ADD_CONTENT_TYPE_TO_SECTION,
    REMOVE_CONTENT_TYPE_FROM_SECTION,
    ADD_ACTIVE_SECTION,
    REMOVE_ACTIVE_SECTION,
    SET_BUTTON_TYPE,
    ADD_TOOLBOX_TYPE,
    REMOVE_TOOLBOX_TYPE,
    ADD_STYLES_TO_CURRENT_SELECTION,
    API_GET_FONTS,
    API_GET_FONTS_SUCCESS,
    ADD_IMAGE_TO_SECTION,
    ZOOM_IN,
    ZOOM_OUT,
    ROTATE_COUNTERCLOCKWISE,
    ROTATE_CLOCKWISE,
    SET_IMAGE_POSITION,
    SET_IMAGE_SIZE,
    SET_CANVAS_SIZE,
    EDIT_TEXT,
    API_SAVE_TEMPLATE,
    API_SAVE_TEMPLATE_SUCCESS,
    REMOVE_GENERATED_IMAGES,
    SAVE_GENERATED_CARD,
    API_GENERATE_ADD_TO_CART_PDF,
    API_GENERATE_ADD_TO_CART_PDF_SUCCESS,
    LOGGED_IN,
    API_ADD_DISCOUNT,
    API_ADD_DISCOUNT_SUCCESS,
    API_GET_ADDRESSES,
    API_GET_ADDRESSES_SUCCESS,
    API_ADD_ADDRESS,
    API_ADD_ADDRESS_SUCCESS,
    API_REMOVE_ADDRESS,
    API_REMOVE_ADDRESS_SUCCESS,
    API_ADD_MULTIPLE_ADDRESSES,
    ADD_BASKET_ERRORS,
    REMOVE_BASKET_ERRORS,
    API_GET_ADDRESS_SUGGESTIONS,
    API_GET_ADDRESS_SUGGESTIONS_SUCCESS,
    API_GET_POSTCODE_SUGGESTIONS,
    REMOVE_SUGGESTIONS,
    UPLOAD_REQUEST,
    UPLOAD_PROGRESS,
    UPLOAD_FAILURE,
    LOGIN_USER,
    LOGIN_USER_ERRORS,
    REGISTER_USER,
    REGISTER_USER_ERRORS,
    FILL_PREVIEW,
    API_GET_USER_DETAILS,
    API_GET_USER_DETAILS_SUCCESS,
    API_ADD_SEND_ON_DATE,
    API_GET_CART_CONTENT,
    API_GET_CART_CONTENT_SUCCESS,
    API_CHANGE_CART_ITEM_QUANTITY,
    API_UPDATE_CART_KEY,
    API_ADD_ADDRESS_AND_DEFAULT_POSTAGE,
    API_ADD_MULTIPLE_ADDRESSES_AND_DEFAULT_POSTAGE,
    API_ADD_POSTAGE_AND_DELAYED_DELIVERY,
    API_ATTACH_GIFT_TO_CARD
} from './actionTypes'

export const {
    addOriginalImages,
    addProductId,
    addProductFormId,
    addEndpoint,
    addTemplateToPage,
    removeTemplateFromPage,
    addContentTypeToSection,
    removeContentTypeFromSection,
    addActiveSection,
    removeActiveSection,
    setButtonType,
    addToolboxType,
    removeToolboxType,
    addStylesToCurrentSelection,
    apiGetFonts,
    apiGetFontsSuccess,
    addImageToSection,
    zoomIn,
    zoomOut,
    rotateCounterclockwise,
    rotateClockwise,
    setImagePosition,
    setImageSize,
    setCanvasSize,
    editText,
    apiSaveTemplate,
    apiSaveTemplateSuccess,
    removeGeneratedImages,
    saveGeneratedCard,
    apiGenerateAddToCartPdf,
    apiGenerateAddToCartPdfSuccess,
    loggedIn,
    apiAddDiscount,
    apiAddDiscountSuccess,
    apiGetAddresses,
    apiGetAddressesSuccess,
    apiAddAddress,
    apiAddAddressSuccess,
    apiRemoveAddress,
    apiRemoveAddressSuccess,
    apiAddMultipleAddresses,
    addBasketErrors,
    removeBasketErrors,
    apiGetAddressSuggestions,
    apiGetAddressSuggestionsSuccess,
    apiGetPostcodeSuggestions,
    removeSuggestions,
    uploadRequest,
    uploadProgress,
    uploadFailure,
    loginUser,
    loginUserErrors,
    registerUser,
    registerUserErrors,
    fillPreview,
    apiGetUserDetails,
    apiGetUserDetailsSuccess,
    apiAddSendOnDate,
    apiGetCartContent,
    apiGetCartContentSuccess,
    apiChangeCartItemQuantity,
    apiUpdateCartKey,
    apiAddAddressAndDefaultPostage,
    apiAddMultipleAddressesAndDefaultPostage,
    apiAddPostageAndDelayedDelivery,
    apiAttachGiftToCard
} = createActions({
    [ADD_ORIGINAL_IMAGES]: null,
    [ADD_PRODUCT_ID]: null,
    [ADD_PRODUCT_FORM_ID]: null,
    [ADD_ENDPOINT]: null,
    [ADD_TEMPLATE_TO_PAGE]: null,
    [REMOVE_TEMPLATE_FROM_PAGE]: null,
    [ADD_CONTENT_TYPE_TO_SECTION]: null,
    [REMOVE_CONTENT_TYPE_FROM_SECTION]: null,
    [ADD_ACTIVE_SECTION]: null,
    [REMOVE_ACTIVE_SECTION]: null,
    [SET_BUTTON_TYPE]: null,
    [ADD_TOOLBOX_TYPE]: null,
    [REMOVE_TOOLBOX_TYPE]: null,
    [ADD_STYLES_TO_CURRENT_SELECTION]: null,
    [API_GET_FONTS]: null,
    [API_GET_FONTS_SUCCESS]: null,
    [ADD_IMAGE_TO_SECTION]: null,
    [ZOOM_IN]: null,
    [ZOOM_OUT]: null,
    [ROTATE_COUNTERCLOCKWISE]: null,
    [ROTATE_CLOCKWISE]: null,
    [SET_IMAGE_POSITION]: null,
    [SET_IMAGE_SIZE]: null,
    [SET_CANVAS_SIZE]: null,
    [EDIT_TEXT]: null,
    [API_SAVE_TEMPLATE]: null,
    [API_SAVE_TEMPLATE_SUCCESS]: null,
    [REMOVE_GENERATED_IMAGES]: null,
    [SAVE_GENERATED_CARD]: null,
    [API_GENERATE_ADD_TO_CART_PDF]: null,
    [API_GENERATE_ADD_TO_CART_PDF_SUCCESS]: null,
    [LOGGED_IN]: null,
    [API_ADD_DISCOUNT]: null,
    [API_ADD_DISCOUNT_SUCCESS]: null,
    [API_GET_ADDRESSES]: null,
    [API_GET_ADDRESSES_SUCCESS]: null,
    [API_ADD_ADDRESS]: null,
    [API_ADD_ADDRESS_SUCCESS]: null,
    [API_REMOVE_ADDRESS]: null,
    [API_REMOVE_ADDRESS_SUCCESS]: null,
    [API_ADD_MULTIPLE_ADDRESSES]: null,
    [ADD_BASKET_ERRORS]: null,
    [REMOVE_BASKET_ERRORS]: null,
    [API_GET_ADDRESS_SUGGESTIONS]: null,
    [API_GET_ADDRESS_SUGGESTIONS_SUCCESS]: null,
    [API_GET_POSTCODE_SUGGESTIONS]: null,
    [REMOVE_SUGGESTIONS]: null,
    [UPLOAD_REQUEST]: null,
    [UPLOAD_PROGRESS]: null,
    [UPLOAD_FAILURE]: null,
    [LOGIN_USER]: null,
    [LOGIN_USER_ERRORS]: null,
    [REGISTER_USER]: null,
    [REGISTER_USER_ERRORS]: null,
    [FILL_PREVIEW]: null,
    [API_GET_USER_DETAILS]: null,
    [API_GET_USER_DETAILS_SUCCESS]: null,
    [API_ADD_SEND_ON_DATE]: null,
    [API_GET_CART_CONTENT]: null,
    [API_GET_CART_CONTENT_SUCCESS]: null,
    [API_CHANGE_CART_ITEM_QUANTITY]: null,
    [API_UPDATE_CART_KEY]: null,
    [API_ADD_ADDRESS_AND_DEFAULT_POSTAGE]: null,
    [API_ADD_MULTIPLE_ADDRESSES_AND_DEFAULT_POSTAGE]: null,
    [API_ADD_POSTAGE_AND_DELAYED_DELIVERY]: null,
    [API_ATTACH_GIFT_TO_CARD]: null
})
