name: merge changes from pre_develop to develop

on:
  pull_request:
    branches: 
      - pre_development
      - pre_master
      - pre_staging
    types: [closed]

jobs:
  shop_deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: echo base branch
        run: echo '${{ github.event.pull_request.base.ref }}'
      - name: echo head branch
        run: echo '${{ github.event.pull_request.head.ref }}'
      - name: setup SHOP_BRANCH env variable
        run: echo "SHOP_BRANCH=$(echo "${{ github.event.pull_request.base.ref }}" | sed "s/pre_//g")" >> $GITHUB_ENV
      - name: echo SHOP_BRANCH branch
        run: echo ${{ env.SHOP_BRANCH }}
      - name: Checkout of ${{ github.event.pull_request.base.ref }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.pull_request.base.ref }}
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Checkout of ${{ env.SHOP_BRANCH }}
        uses: actions/checkout@v2
        with:
          path: ${{ env.SHOP_BRANCH }}
          ref: ${{ env.SHOP_BRANCH }}
      - name: rsync files between both directories
        run: rsync -avh --exclude={'.git','settings_data.json','settings_schema.json','.shopifyignore'} ${{ github.event.pull_request.base.ref }}/ ${{ env.SHOP_BRANCH }}/ --delete
      - name: commit files from the ${{ env.SHOP_BRANCH }}
        run: cd ${{ env.SHOP_BRANCH }}/ && git config --global user.name  "Tom Pepper" && git config --global user.email "tompepper@scribbler.com" && git add . && git commit -a -m "git action push from ${{ github.event.pull_request.base.ref }} by merging of ${{ github.event.pull_request.head.ref }}" && git push
      


        
